Bullboard auth
SysSn13/leetcode-rating-predictor pull request #11
Opened 2021-08-28 06:10 UTC by VidithM

For issue #9. Now, whenever the background is running and we go to /bull-board, if we are not authenticated we are first redirected to a login page. The login credentials can be configured in .env.

2021-08-28 09:08 UTC, SysSn13 commented
Please remove unnecessary changes. I think you recompiled the node addon.

2021-08-29 01:51 UTC, VidithM commented
How about now?

2021-08-29 03:48 UTC, SysSn13 commented
You have deleted too much stuff, unstage those changes instead of deleting files.

2021-08-29 03:57 UTC, SysSn13 commented
This is not how it works. You should reset your commits and then stage only desired changes.

2021-08-29 04:00 UTC, VidithM commented
Sorry, I am working on it. I'll comment when I get the right version

2021-08-29 04:13 UTC, VidithM commented
Ok, I think it should be good now? Let me know.

2021-09-02 19:37 UTC, SysSn13 requested changes

2021-09-02 19:37 UTC, SysSn13 commented on background.js
> +serverAdapter.getRouter();
No use.

2021-09-02 19:37 UTC, SysSn13 commented on main.js
> +    app.use(session({secret : 'keyboard cat'}));
use SESSION_SECRET env variable for express-session secret.

2021-09-02 19:37 UTC, SysSn13 commented on main.js
> +        webRouter.unless({
Is this really required?

2021-09-02 19:37 UTC, SysSn13 commented on routes/auth.js
> +    //console.log('Received login');
remove it

2021-09-02 19:37 UTC, SysSn13 commented on routes/auth.js
> +        return cb(null, { user: 'bull-board' });
can we pass BULLBOARD_USERNAME instead of the default 'bull-board' value

2021-09-02 19:37 UTC, SysSn13 commented on main.js
>      app.use(expressLayouts);
move it top along with other middleware, It is required for login view too

2021-09-02 22:42 UTC, VidithM commented
I also added a 404 page for invalid paths

2021-09-04 04:07 UTC, SysSn13 approved these changes

2021-09-04 04:10 UTC, SysSn13 approved these changes

2021-09-04 04:11 UTC, merged